management:
  endpoints:
    web:
      exposure:
        include: info,health,prometheus
  metrics:
    export:
      prometheus:
        enabled: true
    tags:
      application: ${APP_NAME:notset}
      instance: ${management.metrics.tags.application}-0
