management:
  endpoints:
    metrics:
      enabled: true
    web:
      exposure:
        include: info,health,metrics

  metrics:
    export:
      prometheus:
        enabled: true
        rsocket:
          enabled: true
          host: localhost
          port: 7171
          max-retries: 1000
          first-backoff: 10s
          max-backoff: 5m
    tags:
      application: ${APP_NAME:notset}
      instance: ${management.metrics.tags.application}-0
