server:
  port: 8080

backend:
  baseUrl: http://localhost:9090
  connectionTimeoutMillis: 50
  readTimeoutMillis: 150

resilience4j.circuitbreaker:
  instances:
    backend:
      slidingWindowSize: 50
      minimumNumberOfCalls: 50
      permittedNumberOfCallsInHalfOpenState: 25
      slidingWindowType: COUNT_BASED
      waitDurationInOpenState: 5s
      failureRateThreshold: 50
#      slowCallDurationThreshold: 100
