{
 "title": "Circuit Breakers",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "application",
    "label": "Application",
    "query": "label_values(resilience4j_circuitbreaker_state, application)"
   },
   {
    "name": "instance",
    "label": "Instance",
    "query": "label_values(resilience4j_circuitbreaker_state{application=\"$application\"}, instance)"
   },
   {
    "name": "name",
    "label": "Name",
    "query": "label_values(resilience4j_circuitbreaker_state{application=\"$application\", instance=\"$instance\"}, name)"
   }
  ]
 },
 "panels": [
  {
   "title": "Current State",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "resilience4j_circuitbreaker_state{application=\"$application\", instance=\"$instance\", name=\"$name\"}",
     "legendFormat": "{{state}}"
    }
   ]
  },
  {
   "title": "Latency",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 5 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "rate(resilience4j_circuitbreaker_calls_seconds_sum{application=\"$application\", instance=\"$instance\", name=\"$name\"}[1m])/rate(resilience4j_circuitbreaker_calls_seconds_count{application=\"$application\", instance=\"$instance\", name=\"$name\"}[1m])",
     "legendFormat": "{{kind}}"
    }
   ]
  },
  {
   "title": "Throughput",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 13 },
   "yaxes": [
    { "format": "opm" }
   ],
   "targets": [
    {
     "expr": "rate(resilience4j_circuitbreaker_calls_seconds_count{application=\"$application\", instance=\"$instance\", name=\"$name\"}[1m]) * 60",
     "legendFormat": "{{kind}}"
    }
   ]
  }
 ]
}