---
version: "3"
services:

  grafana:
    image: grafana/grafana:7.1.0
    container_name: metrics-grafana
    volumes:
      - "./datasource.yaml:/etc/grafana/provisioning/datasources/datasource.yaml"
      - "./grafana.ini:/etc/grafana/grafana.ini"
    ports:
    - "3131:3000"

  prometheus:
    image: prom/prometheus:v2.20.0
    container_name: metrics-prometheus
    volumes:
      - "./prometheus.yml:/etc/prometheus/prometheus.yml"
    ports:
      - "9191:9090"

  rproxy:
    image: micrometermetrics/prometheus-rsocket-proxy:1.0.0
    container_name: metrics-rproxy
    ports:
    - "8181:8080"
    - "7171:7001"