global:
  scrape_interval: 5s
  scrape_timeout: 1s
  evaluation_interval: 2s

scrape_configs:

- job_name: 'rproxy'
  metrics_path: '/metrics/connected'
  honor_labels: true
  static_configs:
  - targets: ['rproxy:8080']
