global:
  scrape_interval: 5s
  scrape_timeout: 1s
  evaluation_interval: 2s

scrape_configs:
- job_name: 'frontend'
  metrics_path: '/actuator/prometheus'
  honor_labels: true
  static_configs:
    - targets: ['salmac.lan:8080']
- job_name: 'backend'
  metrics_path: '/actuator/prometheus'
  honor_labels: true
  static_configs:
    - targets: ['salmac.lan:9090']
