apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  labels:
    tier: monitoring
    app: prometheus
data:
  prometheus.yml: |-
    global:
      scrape_interval: 5s
      scrape_timeout: 1s
      evaluation_interval: 2s

    scrape_configs:

    - job_name: 'prometheus'
      static_configs:
      - targets: ['localhost:9090']

    - job_name: 'rsproxy'
      metrics_path: '/metrics/connected'
      honor_labels: true
      kubernetes_sd_configs:
        - role: pod
          namespaces:
            names:
              - default
      relabel_configs:
        - source_labels: [__meta_kubernetes_pod_label_app]
          action: keep
          regex: prometheus-rsproxy
        - source_labels: [__meta_kubernetes_pod_label_tier]
          action: keep
          regex: monitoring
        - source_labels: [__meta_kubernetes_pod_container_port_number]
          action: keep
          regex: 8080
