apiVersion: v1
kind: ServiceAccount
metadata:
  name: prometheus-account
  labels:
    tier: monitoring
    app: prometheus
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: prometheus-role
  labels:
    tier: monitoring
    app: prometheus
rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["watch", "get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: RoleBinding
metadata:
  name: prometheus-binding
  labels:
    tier: monitoring
    app: prometheus
subjects:
  - kind: ServiceAccount
    name: prometheus-account
roleRef:
  kind: Role
  name: prometheus-role
  apiGroup: rbac.authorization.k8s.io
