apiVersion: v1
kind: Service
metadata:
  name: grafana
  labels:
    tier: monitoring
    app: grafana
spec:
  type: LoadBalancer
  selector:
    app: grafana
  ports:
    - name: web
      port: 3131
      targetPort: web