apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-config
  labels:
    tier: monitoring
    app: grafana
data:
  datasource.yaml: |-
    apiVersion: 1
    datasources:
    - name: prometheus
      type: prometheus
      access: proxy
      orgId: 1
      url: http://prometheus:9090
      isDefault: true
  grafana.ini: |-
    [auth.anonymous]
    enabled = true

    # Organization name that should be used for unauthenticated users
    org_name = Main Org.

    # Role for unauthenticated users, other valid values are `Editor` and `Admin`
    org_role = Viewer
  dashboards.yaml: |-
    apiVersion: 1
    providers:
      - name: 'prometheus'
        orgId: 1
        folder: ''
        folderUid: ''
        type: file
        disableDeletion: true
        editable: false
        updateIntervalSeconds: 60
        allowUiUpdates: false
        options:
          path: /var/lib/grafana/dashboards
